### ISSUE TITLE
Automated installation script on Ubuntu 18.10

### ISSUE THREAD

**Issue by zdomjus60** [DFRobot/uPyCraft_src#11]
Not an issue, really. I found that compiling from source can lead to unexpected fails, so I wrote a short script in order to use available resources from the ubuntu repository. The script **must** be made executable the normal way: _sudo chmod a+x uPyCraft_installation.txt_ then executed _./uPyCraft_installation.txt_. This script has worked fine in three different ubuntu machines, I think it can be optimized. The final executable **uPyCraft** can be found in _uPyCraft_src/dist_ directory. 
Hope to be of some usefulness. 
[uPyCraft_installation.txt](https://github.com/DFRobot/uPyCraft/files/2538973/uPyCraft_installation.txt)
Tested on Bodhi (Ubuntu 18.04 based) and Antix (Debian stretch based, 32 bits version), it works fine. If the script crashes on pyinstaller installation, try this command from command line:
pip3 install --upgrade setuptools then relaunch the script.

**Comment by ouki-wang** [comment]
Thank you very much, I have received this document. Currently Linux only supports one version, the next version will integrate your results. Thanks again

**Comment by zdomjus60** [comment]
Thank you ouki-wang, uPyCraft is a wonderful piece of software and makes using Micropython on esp32 and esp8266 boards a breeze. Perharps my script is a little cumbersome, but it gets all needed software parts from common repositories, without extra compiling. I'm absolutely not an expert, but I'm glad to contribute.

**Comment by patfrench** [comment]
Hi all,
I'm french, sorry for my english. I have a problem on linux mint 18 sarah (i386), after run a automatic script

`~/Téléchargements/uPyCraft_src/dist $ ./uPyCraft 
Fatal Python error: Py_Initialize: Unable to get the locale encoding
LookupError: unknown encoding: UTF-8

Current thread 0xb7563980 (most recent call first):
Abandon
`
you can help me ?

**Comment by patfrench** [comment]
problem found for encoding UTF8, (enum34 not compatible) 
pip3 uninstall enum34  

problem found for setuptools (installation of pyinstaller)
sudo apt-get install python3-setuptools

Now new problem :-(
`~/Téléchargements/uPyCraft_src/dist $ ./uPyCraft 
Traceback (most recent call last):
  File "uPyCraft.py", line 2, in <module>
ModuleNotFoundError: No module named 'PyQt4'
[15456] Failed to execute script uPyCraft`

**Comment by zdomjus60** [comment]
@patfrench I had similar problems with my script in linux mint 19, above all with python3 and pyinstaller. Try running my script, it's downloadable from the very first message. As I suggested before, if it crashes during pyinstaller execution, try 
**sudo pip3 install --upgrade setuptools** 
and relaunch the script. Setuptools can be tricky sometimes.

**Comment by patfrench** [comment]
hi
i don't understand, i have launch your script.
Your script is perfect = no error

i have an error here :
` ~/Téléchargements/uPyCraft_src/dist $ ./uPyCraft
Traceback (most recent call last):
  File "uPyCraft.py", line 4, in <module>
ImportError: cannot import name 'Qsci'
[13865] Failed to execute script uPyCraft`

i am on anaconda, may be a problem of path ?

thanks

**Comment by zdomjus60** [comment]
@patfrench To replicate your problem,  I have installed linux mint 18 and anaconda in a virtual machine, I have run the script and the result is a full working executable (I should say aggregate, pyinstaller doesn't create a true compiled executable). Unfortunately, trying to run the uPyCraft.py file in IDLE3 it crashes miserably at the first lines, because it doesn't find the Qt4 module. 
As a workaround you can try to modify the uPyCraft.py file adding two lines of code at the very beginning:
```
import sys
sys.path.append('/usr/lib/python3/dist-packages')
```
you should check the path for the presence of Qt4 module. Save the file. Try to run in IDLE3 or other suitable python ide and check for further errors.

**Comment by patfrench** [comment]
Hi,
I have re-install Linux yesterday (Linux mint 19 64bits) and no problem for install uPycarft.
I have launch your script without problem. 

_For Linux sarah 32bits with anaconda3, i don't know !?!?!?!?!?!? I abandoned ..._

Thank you very much

**Comment by wr300000** [comment]
hi zdomjus60
thank, it's success to bring up uPycraft on my Dell 64bit ubuntu 18.04.2 64bit desktop and my ole Toshiba NB200 Intel Atom N280 cpu, with Mint 19.1 Mate 32bit. It seems that we need to do "pip3 install --upgrade setuptools" after first run as your suggestion on my both laptops. thank you for your kindness

**Comment by Qudor-Engineer** [comment]
> @patfrench To replicate your problem, I have installed linux mint 18 and anaconda in a virtual machine, I have run the script and the result is a full working executable (I should say aggregate, pyinstaller doesn't create a true compiled executable). Unfortunately, trying to run the uPyCraft.py file in IDLE3 it crashes miserably at the first lines, because it doesn't find the Qt4 module.
> As a workaround you can try to modify the uPyCraft.py file adding two lines of code at the very beginning:
> 
> ```
> import sys
> sys.path.append('/usr/lib/python3/dist-packages')
> ```
> 
> you should check the path for the presence of Qt4 module. Save the file. Try to run in IDLE3 or other suitable python ide and check for further errors.

Thank you, your solution working fine on Ubuntu 18.04

**Comment by ioseluiz** [comment]
Thanks! It worked.
